top = '..'

def build(bld):
    # Unit tests
    if bld.env['WITH_TESTS']:
        unit_test_main = bld(
            target='unit-tests-main',
            name='unit-tests-main',
            features='cxx',
            source=bld.path.ant_glob(['**/*.cpp']),
            use='autondn-objects',
          )

        # autondn tests
        unit_tests_autondn = bld.program(
            target='../unit-tests-auto-ndn',
            features='cxx cxxprogram',
            source=bld.path.ant_glob(['autondn/**/*.cpp']),
            use='nlsr-objects unit-tests-main',
            includes='.',
            install_path=None,
            lib=['wiringPi']
          )
